[project]
name = "ddd-demo"
version = "0.1.0"
description = "This is a Domain-Driven Design demo repo."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "httpx>=0.28.1",
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
    "uvicorn>=0.40.0",
]
